name: ci-cd-express-03
on:
  push:
    branches:
      - 'main'
jobs:

  code-test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repository
        uses: actions/checkout@v4.2.2
      - name: Setup Node Environment
        uses: actions/setup-node@v4.3.0
      - name: Code Testing
        run: echo "Test successfull"
  
  build-and-push:
    needs: code-test
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repository
        uses: actions/checkout@v4.2.2
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build Image and Push
        uses: docker/build-push-action@v6.15.0
        with:
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/express-03:${{github.sha}}

  deployment:
      needs: build-and-push
      runs-on: ubuntu-latest
      steps:
        - name: Pull Repository
          uses: actions/checkout@v4.2.2
          with:
              repository: ianPlasabas/argocd-config
              path: express-03
              ssh-key: ${{secrets.SSH_KEY}}
        - name: Modify image name
          run: |
            cd express-03
            git config --global user.name "github.actions"
            git config --global user.email "github.actions@noreply.com"

            sed -i "s#image: .*#image: ${{secrets.DOCKERHUB_USERNAME}}/express-03:${{github.sha}}#" "express-03/deployment.yaml"

            git add .
            git commit -m "Updated image of express-03/deployment.yaml with ${{secrets.DOCKERHUB_USERNAME}}/express-03:${{github.sha}}"
            git push origin HEAD

            